import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/useContext";
import { Toaster } from "@/components/ui/sonner";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "700", "900"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
       </head> 
      <body
        className={`${poppins.variable}  antialiased`}
      >
        <UserProvider>
        {children}
        <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
